language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/names_greeted_test

node_js:
  - "v8.10.0"

services:
  - postgresql

before_script:
  - psql -c 'create database  names_greeted_test;' -U postgres
  - psql -U postgres -d names_greeted_test -a -f database.sql

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2
